apiVersion: v1
kind: Service
metadata:
  name: service-nginx
  labels:
    app:nginx-app  
spec:
  selector:
    app: nginx-app
  type: NodePort
  ports:
  - nodeort: 3001
    port: 80 
    targetport: 80
 

